DROP TABLE TB_CLIENTE;
DROP TABLE TB_LOJISTA;

CREATE TABLE TB_CLIENTE(
    ID VARCHAR2(36) PRIMARY KEY,
    CPF VARCHAR2(11),
    NOME VARCHAR2(50),
    ENDERECO VARCHAR2(100),
    EMAIL VARCHAR2(50),
    SENHA VARCHAR2(20)
);


CREATE TABLE TB_LOJISTA(
    ID VARCHAR2(36) PRIMARY KEY,
    CNPJ VARCHAR2(11),
    NOME VARCHAR2(50),
    ENDERECO VARCHAR2(100),
    EMAIL VARCHAR2(50),
    SENHA VARCHAR2(20),
    TIPO_EMPRESA VARCHAR2(30),
    CATEGORIA_EMPRESA VARCHAR2(30)
);

