DROP TABLE TB_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE TB_LOJISTA CASCADE CONSTRAINTS;

CREATE TABLE TB_CLIENTE (
    ID        VARCHAR2(36)  PRIMARY KEY,
    CPF       VARCHAR2(11)  NOT NULL UNIQUE,
    NOME      VARCHAR2(100) NOT NULL,
    ENDERECO  VARCHAR2(200) NOT NULL,
    EMAIL     VARCHAR2(150) NOT NULL UNIQUE,
    SENHA     VARCHAR2(255) NOT NULL
);

CREATE TABLE TB_LOJISTA (
    ID                VARCHAR2(36)  PRIMARY KEY,
    CNPJ              VARCHAR2(14)  NOT NULL UNIQUE,
    NOME              VARCHAR2(100) NOT NULL,
    ENDERECO          VARCHAR2(200) NOT NULL,
    EMAIL             VARCHAR2(150) NOT NULL UNIQUE,
    SENHA             VARCHAR2(255) NOT NULL,
    TIPO_EMPRESA      VARCHAR2(50)  NOT NULL,
    CATEGORIA_EMPRESA VARCHAR2(50)  NOT NULL
);
