-- 1. Unidade Medida Peso
CREATE TABLE TB_UNIDADE_MEDIDA_PESO (
    ID VARCHAR2(36) PRIMARY KEY,
    UNIDADE_MEDIDA_PESO    VARCHAR2(50) NOT NULL
);

-- 2. Unidade Medida Tamanho
CREATE TABLE TB_UNIDADE_MEDIDA_TAMANHO (
    ID VARCHAR2(36) PRIMARY KEY,
    UNIDADE_MEDIDA_TAMANHO    VARCHAR2(50) NOT NULL
);

-- 3. Categoria
CREATE TABLE TB_CATEGORIA (
    ID   VARCHAR2(36) PRIMARY KEY,
    NOME_CATEGORIA VARCHAR2(100) NOT NULL
);

-- 4. Produto
CREATE TABLE TB_PRODUTO (
    ID               VARCHAR2(36) PRIMARY KEY,
    NOME_PRODUTO             VARCHAR2(150) NOT NULL,
    DESCRICAO_PRODUTO        CLOB,
    PRECO                    NUMBER(15,2) NOT NULL,
    ATIVO                    NUMBER(1) NOT NULL, -- 1 para true, 0 para false
    PESO                     NUMBER(15,2),
    ALTURA                   NUMBER(15,2),
    LARGURA                  NUMBER(15,2),
    PROFUNDIDADE             NUMBER(15,2),
    
    -- Chaves Estrangeiras (Id_dependencia)
    ID_CATEGORIA             VARCHAR2(36) NOT NULL,
    ID_UNIDADE_MEDIDA_PESO   VARCHAR2(36),
    UNIDADE_MEDIDA_TAMANHO   VARCHAR2(36),

    FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIA(ID),
    FOREIGN KEY (ID_UNIDADE_MEDIDA_PESO) REFERENCES TB_UNIDADE_MEDIDA_PESO(ID),
    FOREIGN KEY (UNIDADE_MEDIDA_TAMANHO) REFERENCES TB_UNIDADE_MEDIDA_TAMANHO(ID)
);