DROP TABLE TB_COMENTARIOS CASCADE CONSTRAINTS;
DROP TABLE TB_AVALIACAO CASCADE CONSTRAINTS;

CREATE TABLE TB_AVALIACAO (
    ID          VARCHAR2(36) PRIMARY KEY,
    ID_PRODUTO  VARCHAR2(36) NOT NULL,
    ID_CLIENTE  VARCHAR2(36) NOT NULL,
    ID_LOJISTA  VARCHAR2(36) NOT NULL,
    NOTA_PRODUTO NUMBER(1)   NOT NULL,
    NOTA_LOJA    NUMBER(1)   NOT NULL,

    CONSTRAINT CK_NOTA_PRODUTO CHECK (NOTA_PRODUTO BETWEEN 1 AND 5),
    CONSTRAINT CK_NOTA_LOJA    CHECK (NOTA_LOJA    BETWEEN 1 AND 5),
    CONSTRAINT UQ_AVALIACAO    UNIQUE (ID_CLIENTE, ID_PRODUTO),

    CONSTRAINT FK_AV_PRODUTO
        FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID),
    CONSTRAINT FK_AV_CLIENTE
        FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID),
    CONSTRAINT FK_AV_LOJISTA
        FOREIGN KEY (ID_LOJISTA) REFERENCES TB_LOJISTA(ID)
);

-- Entidade Comentario usa @Table(name = "TB_COMENTARIOS")
CREATE TABLE TB_COMENTARIOS (
    ID           VARCHAR2(36)  PRIMARY KEY,
    ID_AVALIACAO VARCHAR2(36)  NOT NULL,
    COMENTARIO   VARCHAR2(500) NOT NULL,

    CONSTRAINT FK_COMENTARIO_AVALIACAO
        FOREIGN KEY (ID_AVALIACAO) REFERENCES TB_AVALIACAO(ID)
);
