CREATE TABLE TB_PEDIDO (
    ID VARCHAR2(36) PRIMARY KEY,
    ID_CLIENTE VARCHAR2(36),
    CODIGO_RASTREAMENTO NUMBER,
    DATA_ENTREGA DATE,
    VALOR_FINAL DOUBLE,

    FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID)
);

CREATE TABLE TB_ITEM_PEDIDO (
    ID VARCHAR2(36) PRIMARY KEY,
    ID_PEDIDO VARCHAR2(36),
    ID_PRODUTO VARCHAR2(36),
    VALOR_ITEM DOUBLE,
    QUANTIDADE VARCHAR2(3),

    FOREIGN KEY (ID_PEDIDO) REFERENCES TB_PEDIDO(ID),
    FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID)
);



