DROP TABLE ITEMPEDIDO CASCADE CONSTRAINTS;
DROP TABLE PEDIDO CASCADE CONSTRAINTS;

-- Entidade Pedido usa @Table(name = "PEDIDO")
CREATE TABLE PEDIDO (
    ID            VARCHAR2(36)  PRIMARY KEY,
    ID_CLIENTE    VARCHAR2(36)  NOT NULL,
    NUMERO_PEDIDO NUMBER        NOT NULL,
    DATA_ENTREGA  DATE          NOT NULL,
    VALOR_FINAL   NUMBER(15,2)  NOT NULL,

    CONSTRAINT FK_PEDIDO_CLIENTE
        FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID)
);

-- Entidade ItemPedido usa @Table(name = "ITEMPEDIDO")
CREATE TABLE ITEMPEDIDO (
    ID         VARCHAR2(36)  PRIMARY KEY,
    ID_PEDIDO  VARCHAR2(36)  NOT NULL,
    ID_PRODUTO VARCHAR2(36)  NOT NULL,
    VALOR_ITEM NUMBER(15,2)  NOT NULL,
    QUANTIDADE NUMBER(10)    NOT NULL,

    CONSTRAINT FK_ITEM_PEDIDO
        FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID),
    CONSTRAINT FK_ITEM_PRODUTO
        FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO(ID)
);
