DROP TABLE TB_ESTOQUE;
CREATE TABLE TB_ESTOQUE (
    ID VARCHAR2(36) PRIMARY KEY,
    ID_RESPONSAVEL NUMBER,
    PESO_TOTAL NUMBER(10,2),
    VALOR_TOTAL NUMBER(10,2),

    CONSTRAINT FK_ESTOQUE_RESPONSAVEL
        FOREIGN KEY (ID_RESPONSAVEL)
        REFERENCES LOJISTA(ID)
);

DROP TABLE TB_SETOR;
CREATE TABLE TB_SETOR (
    ID VARCHAR2(36) PRIMARY KEY,
    NOME VARCHAR2(255),
    NUMERO_CORREDOR NUMBER,
    PRATELEIRAS NUMBER,
    ID_ESTOQUE VARCHAR2(36),

    CONSTRAINT FK_SETOR_ESTOQUE
        FOREIGN KEY (ID_ESTOQUE)
        REFERENCES TB_ESTOQUE(ID)
);