DROP TABLE TB_ESTOQUE_SETOR CASCADE CONSTRAINTS;
DROP TABLE TB_SETOR CASCADE CONSTRAINTS;
DROP TABLE TB_ESTOQUE CASCADE CONSTRAINTS;

CREATE TABLE TB_ESTOQUE (
    ID           VARCHAR2(36)  PRIMARY KEY,
    ID_RESPONSAVEL VARCHAR2(36) NOT NULL,
    PESO_TOTAL   NUMBER(10,2)  NOT NULL,
    VALOR_TOTAL  NUMBER(10,2),

    CONSTRAINT FK_ESTOQUE_RESPONSAVEL
        FOREIGN KEY (ID_RESPONSAVEL) REFERENCES TB_LOJISTA(ID)
);

CREATE TABLE TB_SETOR (
    ID               VARCHAR2(36)  PRIMARY KEY,
    NOME             VARCHAR2(255) NOT NULL,
    NUMEROS_CORREDOR NUMBER(10),
    PRATELEIRA       NUMBER(10)
);

-- Tabela de join gerada pelo @OneToMany sem @JoinColumn em Estoque
CREATE TABLE TB_ESTOQUE_SETOR (
    TB_ESTOQUE_ID VARCHAR2(36) NOT NULL,
    SETORES_ID    VARCHAR2(36) NOT NULL,

    CONSTRAINT PK_ESTOQUE_SETOR PRIMARY KEY (TB_ESTOQUE_ID, SETORES_ID),
    CONSTRAINT FK_ES_ESTOQUE FOREIGN KEY (TB_ESTOQUE_ID) REFERENCES TB_ESTOQUE(ID),
    CONSTRAINT FK_ES_SETOR   FOREIGN KEY (SETORES_ID)    REFERENCES TB_SETOR(ID)
);
