DROP TABLE TB_MENSAGEM;
DROP TABLE TB_TICKET;

CREATE TABLE TB_TICKET (
                           ID               NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           ID_CLIENTE       NUMBER               NOT NULL,
                           TITULO           VARCHAR2(100)        NOT NULL,
                           DESCRICAO        VARCHAR2(500),
                           STATUS           VARCHAR2(50)         NOT NULL,
                           PRIORIDADE       VARCHAR2(50)         NOT NULL,
                           DATA_CRIACAO     TIMESTAMP            DEFAULT CURRENT_TIMESTAMP NOT NULL,
                           DATA_ATUALIZACAO TIMESTAMP            DEFAULT CURRENT_TIMESTAMP NOT NULL,
                           CONSTRAINT PK_TICKET             PRIMARY KEY (ID),
                           CONSTRAINT FK_TICKET_CLIENTE     FOREIGN KEY (ID_CLIENTE)
                               REFERENCES TB_CLIENTE (ID)
);

CREATE TABLE TB_MENSAGEM (
                             ID         NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                             ID_TICKET  NUMBER           NOT NULL,
                             CONTEUDO   VARCHAR2(1000)   NOT NULL,
                             AUTOR      VARCHAR2(100)    NOT NULL,
                             DATA_ENVIO TIMESTAMP        DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             CONSTRAINT PK_MENSAGEM          PRIMARY KEY (ID),
                             CONSTRAINT FK_MENSAGEM_TICKET   FOREIGN KEY (ID_TICKET)
                                 REFERENCES TB_TICKET (ID)
                                 ON DELETE CASCADE
);