CREATE TABLE ESTOQUE (
    ID VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY,
    ID_RESPONSAVEL NUMBER,
    PESO_TOTAL NUMBER(10,2),
    VALOR_TOTAL NUMBER(10,2),

    CONSTRAINT FK_ESTOQUE_RESPONSAVEL
        FOREIGN KEY (ID_RESPONSAVEL)
        REFERENCES LOJISTA(ID)
);

CREATE TABLE SETOR (
    ID VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY,
    NOME VARCHAR2(255),
    NUMERO_CORREDOR NUMBER,
    PRATELEIRAS NUMBER,
    ID_ESTOQUE VARCHAR2(36),

    CONSTRAINT FK_SETOR_ESTOQUE
        FOREIGN KEY (ID_ESTOQUE)
        REFERENCES ESTOQUE(ID)
);