-- Tabela 1: Cartão
CREATE TABLE CARTAO (
    ID_CARTAO VARCHAR2(36) PRIMARY KEY,
    NOME_TITULAR VARCHAR2(100) NOT NULL,
    NUMERO VARCHAR2(16) NOT NULL,
    CVV VARCHAR2(3) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela 2: Pagamento
CREATE TABLE PAGAMENTO (
    ID_PAGAMENTO VARCHAR2(36) PRIMARY KEY,
    VALOR NUMBER(10,2) NOT NULL,
    STATUS_PAGAMENTO VARCHAR2(50) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_CARTAO VARCHAR2(36) NOT NULL,
    CONSTRAINT FK_PAG_CARTAO FOREIGN KEY (ID_CARTAO) REFERENCES CARTAO(ID_CARTAO)