CREATE TABLE TB_TICKET (
    ID               VARCHAR2(36)       DEFAULT SYS_GUID() NOT NULL,
    ID_CLIENTE       VARCHAR2(36)       NOT NULL,
    TITULO           VARCHAR2(200) NOT NULL,
    DESCRICAO        CLOB,
    STATUS           VARCHAR2(50)  NOT NULL,
    PRIORIDADE       VARCHAR2(50)  NOT NULL,
    DATA_CRIACAO      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_ATUALIZACAO  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_TICKET          PRIMARY KEY (ID),
    CONSTRAINT FK_CLIENTE  FOREIGN KEY (ID_CLIENTE)
        REFERENCES TB_CLIENTE (ID)
);

CREATE TABLE TB_MENSAGEM (
    ID          VARCHAR2(36)       DEFAULT SYS_GUID() NOT NULL,
    ID_TICKET   VARCHAR2(36)       NOT NULL,
    CONTEUDO    CLOB          NOT NULL,
    AUTOR       VARCHAR2(200) NOT NULL,
    DATA_ENVIO   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_MENSAGEM        PRIMARY KEY (ID),
    CONSTRAINT FK_MENSAGEM_TICKET FOREIGN KEY (ID_TICKET)
        REFERENCES TICKET (ID)
        ON DELETE CASCADE
);