CREATE TABLE TB_TRANSPORTADORA (
    ID VARCHAR2(36) PRIMARY KEY,
    NOME VARCHAR2(50) NOT NULL,
    PESO_MIN NUMBER(10,2) NOT NULL,
    PESO_MAX NUMBER(10,2) NOT NULL,
    VALOR_BASE NUMBER(10,2) NOT NULL,
    PRAZO_DIAS NUMBER(10) NOT NULL
);

CREATE TABLE TB_ENTREGA (
    ID VARCHAR2(36) PRIMARY KEY,
    STATUS VARCHAR2(36) NOT NULL,
    VALOR_FRETE NUMBER(10,2) NOT NULL,
    PRAZO_DIAS NUMBER(10) NOT NULL,
    ID_PEDIDO VARCHAR2(36) NOT NULL,
    ID_TRANSPORTADORA VARCHAR2(36) NOT NULL,

    CONSTRAINT FK_ENTREGA_TRANSPORTADORA
        FOREIGN KEY (ID_TRANSPORTADORA)
        REFERENCES TB_TRANSPORTADORA(ID)
);